DO $permissions$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'lb_app') THEN
    GRANT USAGE ON SCHEMA app TO lb_app;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA app TO lb_app;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA app TO lb_app;

    ALTER DEFAULT PRIVILEGES IN SCHEMA app
      GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO lb_app;
    ALTER DEFAULT PRIVILEGES IN SCHEMA app
      GRANT USAGE, SELECT ON SEQUENCES TO lb_app;
  END IF;
END
$permissions$;
