-- LB Developers portfolio reference schema
-- Target: Oracle MySQL 8.0.16+ (the first 8.0 release that enforces CHECK constraints)
-- Run this file against an empty, already-provisioned database.
-- Application connections must set their session time zone to UTC.

SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
SET SESSION time_zone = '+00:00';

-- ============================
-- project_categories
-- ============================
CREATE TABLE project_categories (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(80) NOT NULL,
    slug VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    description VARCHAR(500) NULL,
    sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_project_categories_name (name),
    UNIQUE KEY uq_project_categories_slug (slug),
    KEY idx_project_categories_public (is_active, deleted_at, sort_order, name),
    CONSTRAINT chk_project_categories_slug CHECK (slug REGEXP '^[a-z0-9]+(-[a-z0-9]+)*$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Reusable project categories; soft deletion preserves historical classification.';

-- ============================
-- users
-- ============================
CREATE TABLE users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'Argon2id or bcrypt hash generated by the application; never plaintext.',
    role ENUM('owner', 'admin', 'editor') NOT NULL DEFAULT 'owner',
    avatar_url VARCHAR(2048) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_users_email (email),
    KEY idx_users_role (role, is_active, deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Private dashboard identities; designed for one owner but safely supports delegated editors.';

-- ============================
-- user_sessions
-- ============================
CREATE TABLE user_sessions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    token_hash BINARY(32) NOT NULL COMMENT 'SHA-256 digest of the random session token; the raw token is never stored.',
    ip_hash BINARY(32) NULL COMMENT 'Optional keyed hash used for anomaly detection without retaining the raw IP.',
    user_agent VARCHAR(512) NULL,
    last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at DATETIME NOT NULL,
    revoked_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_user_sessions_token_hash (token_hash),
    KEY idx_user_sessions_user_active (user_id, revoked_at, expires_at),
    KEY idx_user_sessions_expiry (expires_at, revoked_at),
    CONSTRAINT fk_user_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_user_sessions_expiry CHECK (expires_at > created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Revocable server-side admin sessions. User deletion cascades because a session has no independent value.';

-- ============================
-- projects
-- ============================
CREATE TABLE projects (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    category_id BIGINT UNSIGNED NOT NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    title VARCHAR(160) NOT NULL,
    slug VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    short_description VARCHAR(500) NOT NULL,
    full_description MEDIUMTEXT NOT NULL,
    thumbnail_url VARCHAR(2048) NULL,
    cover_image_url VARCHAR(2048) NULL,
    live_url VARCHAR(2048) NULL,
    repo_url VARCHAR(2048) NULL,
    status ENUM('draft', 'published', 'archived') NOT NULL DEFAULT 'draft',
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    view_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Cached lifetime total; page_views remains the analytical source.',
    sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    published_at DATETIME NULL,
    meta_title VARCHAR(60) NULL,
    meta_description VARCHAR(160) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_projects_slug (slug),
    KEY idx_projects_public_featured (status, is_featured, deleted_at, sort_order, id),
    KEY idx_projects_category_public (category_id, status, deleted_at, sort_order, id),
    KEY idx_projects_published (status, deleted_at, published_at, id),
    KEY idx_projects_created_by (created_by),
    KEY idx_projects_updated_by (updated_by),
    FULLTEXT KEY ft_projects_search (title, short_description, full_description),
    CONSTRAINT fk_projects_category FOREIGN KEY (category_id) REFERENCES project_categories(id) ON DELETE RESTRICT,
    CONSTRAINT fk_projects_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_projects_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_projects_slug CHECK (slug REGEXP '^[a-z0-9]+(-[a-z0-9]+)*$'),
    CONSTRAINT chk_projects_publish_state CHECK (status <> 'published' OR published_at IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Portfolio projects. Categories are normalized because their values evolve over time.';

-- ============================
-- project_images
-- ============================
CREATE TABLE project_images (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    project_id BIGINT UNSIGNED NOT NULL,
    image_url VARCHAR(2048) NOT NULL,
    alt_text VARCHAR(180) NOT NULL,
    caption VARCHAR(500) NULL,
    width SMALLINT UNSIGNED NULL,
    height SMALLINT UNSIGNED NULL,
    sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    KEY idx_project_images_gallery (project_id, deleted_at, sort_order, id),
    CONSTRAINT fk_project_images_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT chk_project_images_dimensions CHECK ((width IS NULL AND height IS NULL) OR (width > 0 AND height > 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Ordered project galleries. Hard project deletion cascades to dependent image metadata.';

-- ============================
-- skills
-- ============================
CREATE TABLE skills (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(120) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    category ENUM('frontend', 'backend', 'database', 'devops', 'tools', 'soft-skill') NOT NULL,
    proficiency_level TINYINT UNSIGNED NOT NULL,
    icon_url VARCHAR(2048) NULL,
    sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_skills_name (name),
    UNIQUE KEY uq_skills_slug (slug),
    KEY idx_skills_category_order (category, deleted_at, sort_order, name),
    KEY idx_skills_featured (is_featured, deleted_at, sort_order),
    CONSTRAINT chk_skills_proficiency CHECK (proficiency_level BETWEEN 1 AND 100),
    CONSTRAINT chk_skills_slug CHECK (slug REGEXP '^[a-z0-9]+(-[a-z0-9]+)*$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Curated technical and interpersonal skills; categories are a small, fixed presentation taxonomy.';

-- ============================
-- project_skills
-- ============================
CREATE TABLE project_skills (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    project_id BIGINT UNSIGNED NOT NULL,
    skill_id BIGINT UNSIGNED NOT NULL,
    sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_project_skills_pair (project_id, skill_id),
    KEY idx_project_skills_project_order (project_id, sort_order, skill_id),
    KEY idx_project_skills_skill (skill_id, project_id),
    CONSTRAINT fk_project_skills_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT fk_project_skills_skill FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Many-to-many project-to-skill assignments. Project deletion cascades; referenced skills are restricted.';

-- ============================
-- experiences
-- ============================
CREATE TABLE experiences (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    company VARCHAR(160) NOT NULL,
    job_title VARCHAR(160) NOT NULL,
    employment_type ENUM('full-time', 'part-time', 'contract', 'freelance', 'internship', 'volunteer') NOT NULL,
    description TEXT NOT NULL,
    location VARCHAR(160) NULL,
    is_remote BOOLEAN NOT NULL DEFAULT FALSE,
    start_date DATE NOT NULL,
    end_date DATE NULL,
    is_current BOOLEAN NOT NULL DEFAULT FALSE,
    company_logo_url VARCHAR(2048) NULL,
    sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    KEY idx_experiences_timeline (deleted_at, start_date, end_date, sort_order),
    CONSTRAINT chk_experiences_dates CHECK (end_date IS NULL OR end_date >= start_date),
    CONSTRAINT chk_experiences_current CHECK ((is_current = TRUE AND end_date IS NULL) OR (is_current = FALSE))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Employment history displayed as a reverse chronological timeline.';

-- ============================
-- education_entries
-- ============================
CREATE TABLE education_entries (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    institution VARCHAR(180) NOT NULL,
    degree VARCHAR(160) NOT NULL,
    field_of_study VARCHAR(160) NULL,
    grade VARCHAR(50) NULL,
    start_date DATE NOT NULL,
    end_date DATE NULL,
    description TEXT NULL,
    sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    KEY idx_education_timeline (deleted_at, start_date, end_date, sort_order),
    CONSTRAINT chk_education_dates CHECK (end_date IS NULL OR end_date >= start_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Education records; named education_entries to keep the table name plural and unambiguous.';

-- ============================
-- certifications
-- ============================
CREATE TABLE certifications (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(180) NOT NULL,
    issuing_organization VARCHAR(160) NOT NULL,
    issue_date DATE NOT NULL,
    expiry_date DATE NULL,
    credential_id VARCHAR(120) NULL,
    credential_url VARCHAR(2048) NULL,
    sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_certifications_credential (issuing_organization, credential_id),
    KEY idx_certifications_display (deleted_at, issue_date, sort_order),
    CONSTRAINT chk_certifications_dates CHECK (expiry_date IS NULL OR expiry_date >= issue_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Professional credentials; nullable credential IDs remain unique when present.';

-- ============================
-- blog_posts
-- ============================
CREATE TABLE blog_posts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    author_id BIGINT UNSIGNED NULL,
    title VARCHAR(180) NOT NULL,
    slug VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    excerpt VARCHAR(500) NOT NULL,
    content MEDIUMTEXT NOT NULL,
    cover_image_url VARCHAR(2048) NULL,
    status ENUM('draft', 'published', 'archived') NOT NULL DEFAULT 'draft',
    published_at DATETIME NULL,
    reading_time_minutes SMALLINT UNSIGNED NOT NULL COMMENT 'Rounded estimated reading time calculated by the application.',
    view_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Cached lifetime total; page_views remains the analytical source.',
    meta_title VARCHAR(60) NULL,
    meta_description VARCHAR(160) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_blog_posts_slug (slug),
    KEY idx_blog_posts_public (status, deleted_at, published_at, id),
    KEY idx_blog_posts_popular (status, deleted_at, view_count, published_at),
    KEY idx_blog_posts_author (author_id, status, deleted_at),
    FULLTEXT KEY ft_blog_posts_search (title, excerpt, content),
    CONSTRAINT fk_blog_posts_author FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_blog_posts_slug CHECK (slug REGEXP '^[a-z0-9]+(-[a-z0-9]+)*$'),
    CONSTRAINT chk_blog_posts_reading_time CHECK (reading_time_minutes BETWEEN 1 AND 1440),
    CONSTRAINT chk_blog_posts_publish_state CHECK (status <> 'published' OR published_at IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Optional long-form portfolio content with SEO and cached popularity data.';

-- ============================
-- blog_tags
-- ============================
CREATE TABLE blog_tags (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(60) NOT NULL,
    slug VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_blog_tags_name (name),
    UNIQUE KEY uq_blog_tags_slug (slug),
    KEY idx_blog_tags_name (deleted_at, name),
    CONSTRAINT chk_blog_tags_slug CHECK (slug REGEXP '^[a-z0-9]+(-[a-z0-9]+)*$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Reusable blog taxonomy independent of fixed application enums.';

-- ============================
-- blog_post_tags
-- ============================
CREATE TABLE blog_post_tags (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    blog_post_id BIGINT UNSIGNED NOT NULL,
    blog_tag_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_blog_post_tags_pair (blog_post_id, blog_tag_id),
    KEY idx_blog_post_tags_tag (blog_tag_id, blog_post_id),
    CONSTRAINT fk_blog_post_tags_post FOREIGN KEY (blog_post_id) REFERENCES blog_posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_blog_post_tags_tag FOREIGN KEY (blog_tag_id) REFERENCES blog_tags(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Many-to-many post tagging. Either parent hard deletion removes only the relationship row.';

-- ============================
-- testimonials
-- ============================
CREATE TABLE testimonials (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    author_name VARCHAR(120) NOT NULL,
    author_role VARCHAR(120) NULL,
    author_company VARCHAR(160) NULL,
    author_avatar_url VARCHAR(2048) NULL,
    message TEXT NOT NULL,
    rating TINYINT UNSIGNED NOT NULL,
    is_approved BOOLEAN NOT NULL DEFAULT FALSE,
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    approved_at DATETIME NULL,
    sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    KEY idx_testimonials_public (is_approved, is_featured, deleted_at, sort_order, id),
    CONSTRAINT chk_testimonials_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT chk_testimonials_approval CHECK (is_approved = FALSE OR approved_at IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Client recommendations moderated before public display.';

-- ============================
-- contact_messages
-- ============================
CREATE TABLE contact_messages (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(254) NOT NULL,
    subject VARCHAR(180) NOT NULL,
    message TEXT NOT NULL,
    ip_address VARBINARY(16) NULL COMMENT 'Packed IPv4 or IPv6 from INET6_ATON(); apply a short retention policy.',
    user_agent VARCHAR(512) NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    is_replied BOOLEAN NOT NULL DEFAULT FALSE,
    read_at DATETIME NULL,
    replied_at DATETIME NULL,
    submitted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    KEY idx_contact_messages_inbox (is_read, deleted_at, submitted_at, id),
    KEY idx_contact_messages_reply_queue (is_replied, deleted_at, submitted_at, id),
    KEY idx_contact_messages_sender (email, submitted_at),
    CONSTRAINT chk_contact_messages_name CHECK (CHAR_LENGTH(name) BETWEEN 2 AND 120),
    CONSTRAINT chk_contact_messages_message CHECK (CHAR_LENGTH(message) BETWEEN 10 AND 10000),
    CONSTRAINT chk_contact_messages_read CHECK ((is_read = FALSE AND read_at IS NULL) OR (is_read = TRUE AND read_at IS NOT NULL)),
    CONSTRAINT chk_contact_messages_replied CHECK ((is_replied = FALSE AND replied_at IS NULL) OR (is_replied = TRUE AND replied_at IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Inbound portfolio inquiries with explicit inbox and reply workflow state.';

-- ============================
-- social_links
-- ============================
CREATE TABLE social_links (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    platform VARCHAR(50) NOT NULL,
    url VARCHAR(2048) NOT NULL,
    icon VARCHAR(120) NULL COMMENT 'Icon-library key such as lucide:github; not executable markup.',
    sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_social_links_platform (platform),
    KEY idx_social_links_public (is_active, deleted_at, sort_order, platform)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Ordered public profile links; platform stays data-driven rather than a fixed enum.';

-- ============================
-- site_settings
-- ============================
CREATE TABLE site_settings (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    setting_key VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    setting_value TEXT NULL,
    value_type ENUM('string', 'text', 'url', 'boolean', 'integer', 'json') NOT NULL DEFAULT 'string',
    is_public BOOLEAN NOT NULL DEFAULT TRUE COMMENT 'False values may be returned only to authenticated administrators.',
    description VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_site_settings_key (setting_key),
    KEY idx_site_settings_public (is_public, deleted_at, setting_key),
    CONSTRAINT chk_site_settings_key CHECK (setting_key REGEXP '^[a-z][a-z0-9_]*$'),
    CONSTRAINT chk_site_settings_typed_value CHECK (
        setting_value IS NULL
        OR (
            (value_type <> 'boolean' OR setting_value IN ('true', 'false'))
            AND (value_type <> 'integer' OR setting_value REGEXP '^-?[0-9]+$')
            AND (value_type <> 'json' OR JSON_VALID(setting_value))
        )
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Typed key-value content configuration. Secrets must remain in environment variables, never here.';

-- ============================
-- page_views
-- ============================
CREATE TABLE page_views (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    page_type ENUM('project', 'blog_post', 'page') NOT NULL,
    project_id BIGINT UNSIGNED NULL,
    blog_post_id BIGINT UNSIGNED NULL,
    page_path VARCHAR(500) NULL COMMENT 'Canonical route used only when page_type is page.',
    ip_address VARBINARY(16) NULL COMMENT 'Packed address from INET6_ATON(); hash or purge according to privacy policy.',
    visitor_hash BINARY(32) NULL COMMENT 'Rotating keyed hash for approximate unique-visitor counts.',
    user_agent VARCHAR(512) NULL,
    referrer VARCHAR(2048) NULL,
    viewed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_page_views_project_time (project_id, viewed_at),
    KEY idx_page_views_blog_time (blog_post_id, viewed_at),
    KEY idx_page_views_path_time (page_path, viewed_at),
    KEY idx_page_views_time_type (viewed_at, page_type),
    KEY idx_page_views_visitor_time (visitor_hash, viewed_at),
    CONSTRAINT fk_page_views_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT fk_page_views_blog_post FOREIGN KEY (blog_post_id) REFERENCES blog_posts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Lightweight first-party analytics. The application validates that exactly one target matches page_type.';

-- ============================
-- activity_logs
-- ============================
CREATE TABLE activity_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    actor_user_id BIGINT UNSIGNED NULL,
    action VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'Stable action key such as project.publish.',
    subject_type VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    subject_id BIGINT UNSIGNED NULL COMMENT 'Polymorphic identifier retained for audit history; intentionally has no foreign key.',
    request_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    ip_address VARBINARY(16) NULL,
    metadata JSON NULL COMMENT 'Privacy-reviewed contextual fields only; never tokens, passwords, or message bodies.',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_activity_logs_actor_time (actor_user_id, created_at),
    KEY idx_activity_logs_subject_time (subject_type, subject_id, created_at),
    KEY idx_activity_logs_request (request_id),
    CONSTRAINT fk_activity_logs_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Append-oriented admin audit trail. Actor deletion sets null so historical accountability is retained.';
